CREATE TABLE HELP (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    data VARCHAR(2048) NOT NULL,
    keyboardId INT NOT NULL,
    btn_id INT NOT NULL,
    ordr INT NOT NULL,
    FOREIGN KEY(btn_id) REFERENCES BUTTONS(ID)
);
