CREATE TABLE IDEA_MODES (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mode VARCHAR(255) NOT NULL
);

INSERT INTO IDEA_MODES (mode) VALUES('short');
INSERT INTO IDEA_MODES (mode) VALUES('long');
