INSERT INTO CURRENCIES (descr, code, sign)
VALUES ('United States Dollar', 'USD', '$'),
       ('Euro', 'EUR', '€'),
       ('Japanese Yen', 'JPY', '¥'),
       ('Pound Sterling', 'GBP', '£'),
       ('Swiss Franc', 'CHF', 'Fr.'),
       ('Canadian Dollar', 'CAD', '$'),
       ('Australian Dollar', 'AUD', '$'),
       ('New Zealand Dollar', 'NZD', '$'),
       ('Chinese Yuan', 'CNY', '¥'),
       ('Hong Kong Dollar', 'HKD', '$'),
       ('Swedish Krona', 'SEK', 'kr'),
       ('Norwegian Krone', 'NOK', 'kr'),
       ('Danish Krone', 'DKK', 'kr'),
       ('Singapore Dollar', 'SGD', '$'),
       ('South Korean Won', 'KRW', '₩'),
       ('Indian Rupee', 'INR', '₹'),
       ('Russian Ruble', 'RUB', '₽'),
       ('Brazilian Real', 'BRL', 'R$'),
       ('Mexican Peso', 'MXN', '$'),
       ('South African Rand', 'ZAR', 'R'),
       ('Turkish Lira', 'TRY', '₺'),
       ('Indonesian Rupiah', 'IDR', 'Rp'),
       ('Polish Zloty', 'PLN', 'zł'),
       ('Israeli New Shekel', 'ILS', '₪'),
       ('Saudi Arabian Riyal', 'SAR', 'ر.س'),
       ('United Arab Emirates Dirham', 'AED', 'د.إ'),
       ('Colombian Peso', 'COP', '$'),
       ('Philippine Peso', 'PHP', '₱'),
       ('Egyptian Pound', 'EGP', '£');
