CREATE TABLE CONTINIOUSDAY_prm (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  day_id INT NOT NULL,
  day_start DATE,
  day_end DATE,
  FOREIGN KEY (day_id) REFERENCES DAYS(id) ON DELETE CASCADE
);
