CREATE TABLE WEEKDAY_prm (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  day_id INT NOT NULL,
  weekday TINYINT NOT NULL,
  occurence TINYINT NOT NULL,
  month TINYINT NOT NULL,
  FOREIGN KEY (day_id) REFERENCES DAYS(id)
);
