CREATE TABLE IMAGES (
    ID INT NOT NULL AUTO_INCREMENT,
    img_path VARCHAR(255) NOT NULL,
    idea_id INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (idea_id) REFERENCES IDEAS(id) ON DELETE CASCADE
);
