CREATE TABLE FRIENDS (
    ID INT NOT NULL AUTO_INCREMENT,
    idea_id INT NOT NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (idea_id) REFERENCES IDEAS(ID),
    FOREIGN KEY (user_id) REFERENCES USERS(ID),
    PRIMARY KEY (ID)
);
