INSERT INTO USERS (tg_id, name) VALUES ('1','kekwait;/');
INSERT INTO USERS (tg_id, name) VALUES ('2','gigaman:)');
INSERT INTO USERS (tg_id, name) VALUES ('3','dummymna:(');
INSERT INTO IDEAS(isPublic, descr, price, origin, user_id) VALUES(0, 'dscription1', 100.15, 'kekw.com', 1);
INSERT INTO IDEAS(isPublic, descr, price, origin, user_id) VALUES(0, 'dscription2', 200.15, 'kekw.com', 1);
INSERT INTO IDEAS(isPublic, descr, price, origin, user_id) VALUES(0, 'dscription3', 300.15, 'kekw.com', 2);
INSERT INTO IDEAS(isPublic, descr, price, origin, user_id) VALUES(0, 'dscription3', 400.15, 'kekw.com', 3);
INSERT INTO FRIENDS(idea_id, user_id) VALUES(1,2);
INSERT INTO FRIENDS(idea_id, user_id) VALUES(1,3);
INSERT INTO FRIENDS(idea_id, user_id) VALUES(3,1);
INSERT INTO IMAGES (img_path, idea_id) VALUES ('/path/to/image1.jpg', 1);
INSERT INTO IMAGES (img_path, idea_id) VALUES ('/path/to/image2.jpg', 1);
INSERT INTO IMAGES (img_path, idea_id) VALUES ('/path/to/image3.jpg', 2);
INSERT INTO IMAGES (img_path, idea_id) VALUES ('/path/to/image4.jpg', 3);
